### ISSUE TITLE
Case Undefined when filling all needed information

### ISSUE THREAD

**Issue by haberlea** [nstuyvesant/support#12]
I tried twice to open a ticket for eBay, without luck. Matt opened it without issues few mins later.
Steps to reproduce:
Perfecto.io -> support -> Automation -> execution error -> open new ticket.
 
Filled all the fields with data. The first ticket I’ve attached logs, and after it failed to be created, I’ve tried second time without attaching any files. The result was same. After clicking the submit, instead to see number I see that:

<img width="631" alt="image001" src="https://user-images.githubusercontent.com/14138728/42146440-735c1132-7dd0-11e8-8ed5-8ab1d41fbf86.png">
 
Also no mail was sent to me for the new case.

Here is the data i filled up in the fields:
<img width="497" alt="ticket2" src="https://user-images.githubusercontent.com/14138728/42146644-b45660c4-7dd1-11e8-9b71-5cf4513d7c2a.png">

If you submit exactly the same thing again, will you get the same results? - Yes I tried twice (not sure if i put exact same data in the long description but all other fields were filled the same way). After that I've sent all the info to Matt and he opened a ticket for me without any issues. Please note I had no issues opening other tickets during that day, but in different category (cloud), so it is either problem with that specific category/subcategory and my end or, in general some issue with my location at that moment

**Comment by nstuyvesant** [comment]
Think this may have been related to a new Safari bug that causes new FormData() to fail if a file field is left blank. If so, this would match [issue 11](https://github.com/nstuyvesant/support/issues/11) which was just fixed.

I was not able to reproduce your problem filling out the fields the same way as above (after the fix for issue 11 was applied).

Please verify this on your end so this issue can be closed.

Thanks,
Nate

**Comment by nstuyvesant** [comment]
Resolved.
